name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest --cov=complexifier 

    - name: Free Code Coverage
      uses: SamuelCabralCruz/free-code-coverage/upload-github-repo@v0.0.13

      with:
        github-repo: ruyzambrano/complexifier
        project-name: complexifier 
        coverage-metric: 
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

  update:
    runs-on: ubuntu-latest

    steps:
      - uses: SamuelCabralCruz/free-code-coverage/update-github-repo@v0.0.13
        with:
          github-repo: ruyzambrano/complexifier
          project-name: complexifier
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        
